[env:esp32-poe]
platform = espressif32@6.9.0
board = esp32-poe
framework = arduino
board_build.partitions = min_spiffs.csv
upload_port = COM3
monitor_port = COM3
lib_deps =
    miguelbalboa/MFRC522@^1.4.11
    bblanchon/ArduinoJson@^6.21.5
